services:
  client:
    stdin_open: true
#    user: node:node
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: react-vite-05
    restart: unless-stopped
    ports:
      - "5473:5473"
    volumes:
#      - "react_vite:/app/node_modules"
      - "./:/app"
    command: >
      /bin/sh -c "cp -fu /cache/package-lock.json /app/package-lock.json 
      && cp -rfu /cache/node_modules/. /app/node_modules/ 
      && npm run dev"
volumes:
  react_vite:
    driver: local
    name: react_vite