version: '3'
services:
  client:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: react-app
    restart: unless-stopped
    ports:
      - "5471:5471"
    volumes:
      - "/app/node_modules"
      - "./:/app"
