FROM node:20-alpine
RUN apk update
RUN apk add git
#RUN npm create vite@latest
#RUN npm init create vite@latest
#RUN mkdir /app
WORKDIR /app
#RUN npm create vite@latest test-app -- --template react
#RUN chown -R node:node .
#ADD . /app
